#!/bin/sh

darcs get --partial http://darcs.haskell.org/packages/Cabal/ && \
cd Cabal/epm && \
make && \
sudo make install && \
sudo epm update && \
epm install --prefix=/tmp --user hnop && \
ls -l /tmp/bin/hnop
